# Generated by Django 2.2.1 on 2020-04-21 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:51.280034', max_length=255, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime(2020, 4, 20, 22, 20, 51, 280034))),
                ('imagen', models.ImageField(null=True, upload_to='events/images')),
                ('descripcion', models.CharField(max_length=1000, unique=True)),
                ('lugar', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:51.281032', max_length=255, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime(2020, 4, 20, 22, 20, 51, 281032))),
                ('imagen', models.ImageField(null=True, upload_to='events/images')),
                ('descripcion', models.CharField(max_length=1000, unique=True)),
                ('lugar', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:51.282033', max_length=255, unique=True)),
                ('descripcion', models.CharField(default='Noticias y eventos de la institución.', max_length=1000, unique=True)),
                ('imagen', models.ImageField(upload_to='events/images/')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitio',
            },
        ),
    ]
