# Generated by Django 2.2.1 on 2020-04-29 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200429_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 7, 37, 581469)),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.581469', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 7, 37, 585468)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.585468', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.586466', max_length=255, unique=True),
        ),
    ]
