# Generated by Django 2.2.1 on 2020-04-29 19:38

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200429_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 37, 39, 927448)),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:37:39.927448', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 14, 37, 39, 928450)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:37:39.928450', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:37:39.928450', max_length=255, unique=True),
        ),
    ]
