# Generated by Django 2.2.1 on 2020-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:55.104026', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='gallery/images/')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:55.104026', max_length=255, unique=True)),
                ('descripcion', models.CharField(default='Galería de imagenes de la institución.', max_length=1000, unique=True)),
                ('imagen', models.ImageField(upload_to='gallery/images/')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitio',
            },
        ),
    ]
