# Generated by Django 2.2.1 on 2020-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200420_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-04-29 13:48:01.656242', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-29 13:48:01.657248', max_length=255, unique=True),
        ),
    ]
