# Generated by Django 2.2.1 on 2020-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20200520_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-05-20 15:11:21.075212', max_length=255, unique=True)),
                ('nombre_categoria', models.CharField(default='2020-05-20 15:11:21.075212', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='anio',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.075212', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.077214', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='images',
            name='categorias',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
    ]
