# Generated by Django 2.2.1 on 2020-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20200520_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='images',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:58.982211', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre_categoria',
            field=models.CharField(default='2020-05-22 14:32:58.982211', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:58.980210', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:58.992211', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020', max_length=255, unique=True)),
                ('categorias', models.ManyToManyField(to='gallery.Category')),
                ('images', models.ManyToManyField(to='gallery.Images')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
            },
        ),
    ]
