# Generated by Django 2.2.1 on 2020-05-22 19:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200522_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='anio',
        ),
        migrations.AddField(
            model_name='year',
            name='imagen_tarjeta',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='tarjeta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:35:32.563689', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre_categoria',
            field=models.CharField(default='2020-05-22 14:35:32.564689', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:35:32.562686', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:35:32.569688', max_length=255, unique=True),
        ),
    ]
