# Generated by Django 2.2.1 on 2020-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200522_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.084344', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre_categoria',
            field=models.CharField(default='2020-05-22 14:40:20.084344', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.084344', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.088342', max_length=255, unique=True),
        ),
    ]
