# Generated by Django 2.2.1 on 2020-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20200522_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='images',
            new_name='imagenes',
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.484197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre_categoria',
            field=models.CharField(default='2020-05-22 14:45:33.484197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.484197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.487197', max_length=255, unique=True),
        ),
    ]
