# Generated by Django 2.2.1 on 2020-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Informacion de Contacto',
                'verbose_name_plural': 'Informacion de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:19:21.823894', max_length=255, unique=True)),
                ('descripcion', models.CharField(default='Contacto de la institución.', max_length=1000, unique=True)),
                ('imagen', models.ImageField(upload_to='contact/images/')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitio',
            },
        ),
    ]
