# Generated by Django 2.2.1 on 2020-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-20 22:19:36.563524', max_length=255, unique=True),
        ),
    ]
