# Generated by Django 2.2.1 on 2020-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200420_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-20 22:20:43.889503', max_length=255, unique=True),
        ),
    ]
