# Generated by Django 2.2.1 on 2020-04-29 19:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20200429_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:37:39.924414', max_length=255, unique=True),
        ),
    ]
