# Generated by Django 2.2.1 on 2020-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='howtohelp/images/methods')),
            ],
            options={
                'verbose_name': 'Método de Ayuda',
                'verbose_name_plural': 'Métodos de Ayuda',
            },
        ),
        migrations.CreateModel(
            name='MonetaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='howtohelp/images/monetaryInfo')),
                ('nombre_cuenta', models.CharField(max_length=500, unique=True)),
                ('numero_cuenta', models.CharField(max_length=255, unique=True)),
                ('clabe_cuenta', models.CharField(max_length=255, unique=True)),
                ('sucursal_cuenta', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Información Monetaria',
                'verbose_name_plural': 'Información Monetaria',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:21:04.215511', max_length=255, unique=True)),
                ('descripcion', models.CharField(default='Formas de ayudar a la institución.', max_length=1000, unique=True)),
                ('imagen', models.ImageField(upload_to='howtohelp/images/')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitio',
            },
        ),
    ]
