# Generated by Django 2.2.1 on 2020-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howtohelp', '0014_auto_20200520_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:59.017209', max_length=255, unique=True),
        ),
    ]
