# Generated by Django 2.2.1 on 2020-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='nombre',
            field=models.CharField(default='2020-04-20 22:21:21.644404', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-20 22:21:21.645368', max_length=255, unique=True),
        ),
    ]
