# Generated by Django 2.2.1 on 2020-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20200520_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.103211', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nombre_certificacion',
            field=models.CharField(default='2020-05-20 15:11:21.103211', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.104214', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre_otro',
            field=models.CharField(default='2020-05-20 15:11:21.104214', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.102212', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:11:21.105213', max_length=255, unique=True),
        ),
    ]
