# Generated by Django 2.2.1 on 2020-05-22 19:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20200520_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='certificacion'),
        ),
        migrations.AddField(
            model_name='other',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:59.031207', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nombre_certificacion',
            field=models.CharField(default='2020-05-22 14:32:59.031207', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:59.032209', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre_otro',
            field=models.CharField(default='2020-05-22 14:32:59.032209', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:59.030207', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:32:59.032209', max_length=255, unique=True),
        ),
    ]
