# Generated by Django 2.2.1 on 2020-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200522_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.111343', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nombre_certificacion',
            field=models.CharField(default='2020-05-22 14:40:20.112342', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.112342', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre_otro',
            field=models.CharField(default='2020-05-22 14:40:20.112342', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.111343', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:40:20.113341', max_length=255, unique=True),
        ),
    ]
