# Generated by Django 2.2.1 on 2020-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200522_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.509197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='nombre_certificacion',
            field=models.CharField(default='2020-05-22 14:45:33.509197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.509197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='nombre_otro',
            field=models.CharField(default='2020-05-22 14:45:33.509197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.509197', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-22 14:45:33.510199', max_length=255, unique=True),
        ),
    ]
