# Generated by Django 2.2.1 on 2020-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:57.923048', max_length=255, unique=True)),
                ('textoA', models.CharField(max_length=255, unique=True)),
                ('imagenA', models.ImageField(upload_to='home/images/about')),
                ('textoB', models.CharField(max_length=255, unique=True)),
                ('imagenB', models.ImageField(upload_to='home/images/about')),
                ('textoC', models.CharField(max_length=255, unique=True)),
                ('imagenC', models.ImageField(upload_to='home/images/about')),
            ],
            options={
                'verbose_name': 'Sobre Nosotros',
                'verbose_name_plural': 'Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(default='', upload_to='home/images/directors')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('puesto', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:57.922051', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='home/images')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:57.926050', max_length=255, unique=True)),
                ('mision', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misión',
            },
        ),
        migrations.CreateModel(
            name='Patrons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='home/images/patrons')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('puesto', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Patronato',
                'verbose_name_plural': 'Patrones',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:57.926050', max_length=255, unique=True)),
                ('valor', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:20:57.926050', max_length=255, unique=True)),
                ('vision', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'verbose_name': 'Visión',
                'verbose_name_plural': 'Visión',
            },
        ),
    ]
