# Generated by Django 2.2.1 on 2020-04-29 19:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200429_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.591468', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.590468', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='path',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='home/image'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.593469', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.594466', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.594466', max_length=255, unique=True),
        ),
    ]
