# Generated by Django 2.2.1 on 2020-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200429_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.918793', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directors',
            name='puesto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directors',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.916791', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.921794', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='puesto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patrons',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='values',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.922793', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.921794', max_length=255, unique=True),
        ),
    ]
