# Generated by Django 2.2.1 on 2020-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200511_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.744762', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.743762', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.746147', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.747104', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.747104', max_length=255, unique=True),
        ),
    ]
