# Generated by Django 2.2.1 on 2020-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200511_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Slide de Imágen', 'verbose_name_plural': 'Slides de Imágenes'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:08:28.309794', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:08:28.308794', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:08:28.310794', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:08:28.311795', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2020-05-20 15:08:28.311795', max_length=255, unique=True),
        ),
    ]
