# Generated by Django 2.2.1 on 2020-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Datos',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-04-20 22:21:08.004057', max_length=255, unique=True)),
                ('descripcion', models.CharField(default='Programas de la Institución.', max_length=1000, unique=True)),
                ('imagen', models.ImageField(upload_to='programs/images/')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitio',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(default='None', upload_to='programs/images/programs')),
                ('subtitulo', models.CharField(max_length=255, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=650, null=True, unique=True)),
                ('titulo_datos', models.CharField(max_length=255, null=True, unique=True)),
                ('datos', models.ManyToManyField(to='programs.Data')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
