# Generated by Django 2.2.1 on 2020-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200429_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-04-29 14:07:37.602467', max_length=255, unique=True),
        ),
    ]
