# Generated by Django 2.2.1 on 2020-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200429_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='nombre_dato',
            field=models.CharField(default='2020-05-11 13:59:49.937791', max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.937791', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-11 13:59:49.939791', max_length=255, unique=True),
        ),
    ]
