# Generated by Django 2.2.1 on 2020-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20200511_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Dato', 'verbose_name_plural': 'Datos'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='program',
            name='titulo_datos',
        ),
        migrations.AlterField(
            model_name='data',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.754098', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='nombre_dato',
            field=models.CharField(default='2020-05-11 14:13:45.754098', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='nombre',
            field=models.CharField(default='2020-05-11 14:13:45.758972', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2020-05-11 14:13:45.755100', max_length=255, unique=True)),
                ('titulo_datos', models.CharField(default='2020-05-11 14:13:45.756003', max_length=255, null=True)),
                ('datos', models.ManyToManyField(to='programs.Data')),
            ],
            options={
                'verbose_name': 'Colección Datos',
                'verbose_name_plural': 'Colección Datos',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='colecciones_datos',
            field=models.ManyToManyField(to='programs.DataCollection'),
        ),
    ]
